### ISSUE TITLE
mysterious scroll bar problem

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Eigo-sensei#18]
When the webpage is restored down in the browsers and the top right button is pressed. Upon hitting the language tab and then maximizing the tab again a mysterious scroll bar appears.

If anybody knows how to resolve this issue it would be greatly appreciated. Refer to image below.

![restored down](https://user-images.githubusercontent.com/22683645/31943675-613622ea-b904-11e7-87da-ef0f5fe5d163.png)

**Comment by Harumaro** [comment]
Can't seem to reproduce here, can I get a window resolution and browser used to reproduce?

**Comment by adlyloukil** [comment]
I am using chrome and I am unsure of the resolution but about half the size of a full-screen browser. If you put it to about half the window size then menu that you just adjusted should pop up if you click on the arrow next to the word "English" the Japanese flag should show. If you then maximize the half window back to full screen the issue appears.

**Comment by RickRedSix** [comment]
Hi @adlyloukil, I believe the issue is because the height of the navbar is automatic, so when you are resizing the browser with the language dropdown active, when you resize the window again, the height of the nav bar is wrong for the expanded dropdown. 

Setting the nav bar's overflow to visible, so not scrolling should stop it from appearing. PR here: #20

**Comment by Harumaro** [comment]
Sorry, this is all I see when resizing https://a.uguu.se/51rlCGd7lYrp_2017-10-24_15-36-38.webm
Which is the expected behaviour I guess.

**Comment by adlyloukil** [comment]
@Harumaro looks like @RickRedSix  solved the issue. Thanks a lot both of you.
